// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pathly.Data;

#nullable disable

namespace Pathly.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260319154222_InitialCreateAndSeed")]
    partial class InitialCreateAndSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Pathly.DataModels.ActionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Resources")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RoadmapId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapId");

                    b.HasIndex("UserId");

                    b.ToTable("Actions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCompleted = true,
                            Resources = "MS Docs, Pluralsight",
                            RoadmapId = 1,
                            Title = "Master EF Core",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 2,
                            IsCompleted = false,
                            Resources = "Docker, RabbitMQ basics",
                            RoadmapId = 1,
                            Title = "Learn Microservices",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 3,
                            IsCompleted = false,
                            Resources = "GoF Book",
                            RoadmapId = 1,
                            Title = "System Design Design Patterns",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 4,
                            IsCompleted = true,
                            Resources = "AutoMapper Guide",
                            RoadmapId = 2,
                            Title = "Implement AutoMapper",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 5,
                            IsCompleted = false,
                            Resources = "xUnit, Moq",
                            RoadmapId = 2,
                            Title = "Setup Unit Tests",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 6,
                            IsCompleted = false,
                            Resources = "Bootstrap, CSS",
                            RoadmapId = 2,
                            Title = "Finalize UI",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 7,
                            IsCompleted = true,
                            RoadmapId = 3,
                            Title = "Basic Syntax",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 8,
                            IsCompleted = true,
                            RoadmapId = 3,
                            Title = "Loops and Arrays",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 9,
                            IsCompleted = true,
                            RoadmapId = 3,
                            Title = "Classes and Objects",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        });
                });

            modelBuilder.Entity("Pathly.DataModels.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3f2504e0-4f89-11d3-9a0c-0305e82c3301",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "59410515-1d89-44a8-87ce-b8e89edf7130",
                            Email = "test@pathly.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TEST@PATHLY.COM",
                            NormalizedUserName = "TEST@PATHLY.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAoxW3EMto9W74DoYzxcUOwhnIMveA+g07tCD1LizE3mLIEfmLMkWZMxT0KoQdTscw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b2a9201f-73e8-45ee-8ef1-f7c901aeac00",
                            TwoFactorEnabled = false,
                            UserName = "test@pathly.com"
                        });
                });

            modelBuilder.Entity("Pathly.DataModels.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Goals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            ShortDescription = "Mastering advanced architecture and cloud services in the .NET ecosystem.",
                            TargetDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Become a Senior .NET Developer",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            ShortDescription = "Complete the implementation of AutoMapper and Seeding in the current project.",
                            TargetDate = new DateTime(2026, 4, 19, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6425),
                            Title = "Master Pathly Architecture",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = false,
                            ShortDescription = "Successfully finished the basics of C# programming.",
                            TargetDate = new DateTime(2025, 10, 19, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6465),
                            Title = "SoftUni Fundamentals Module",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        });
                });

            modelBuilder.Entity("Pathly.DataModels.Roadmap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GoalId")
                        .HasColumnType("int");

                    b.Property<string>("IdealOutcome")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Why")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("GoalId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Roadmaps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GoalId = 1,
                            IdealOutcome = "Senior Dev Role",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301",
                            Why = "To achieve financial independence"
                        },
                        new
                        {
                            Id = 2,
                            GoalId = 2,
                            IdealOutcome = "Perfectly coded app",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301",
                            Why = "To build professional habits"
                        },
                        new
                        {
                            Id = 3,
                            GoalId = 3,
                            IdealOutcome = "Solid programming basics",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301",
                            Why = "Foundation is key"
                        });
                });

            modelBuilder.Entity("Pathly.DataModels.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Work",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Personal",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 3,
                            Name = "C#",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gym",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Frontend",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Testing",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Learning",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Soft Skill",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 9,
                            Name = "School",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Urgent",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        });
                });

            modelBuilder.Entity("Pathly.DataModels.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionId = 1,
                            CreatedOn = new DateTime(2026, 3, 9, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6763),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6767),
                            IsCompleted = true,
                            Priority = 3,
                            Title = "Task 1 for Action 1",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 2,
                            ActionId = 1,
                            CreatedOn = new DateTime(2026, 3, 9, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6771),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6772),
                            IsCompleted = false,
                            Priority = 4,
                            Title = "Task 2 for Action 1",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 3,
                            ActionId = 1,
                            CreatedOn = new DateTime(2026, 3, 9, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6774),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6775),
                            IsCompleted = true,
                            Priority = 1,
                            Title = "Task 3 for Action 1",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 4,
                            ActionId = 2,
                            CreatedOn = new DateTime(2026, 3, 9, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6777),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6778),
                            IsCompleted = false,
                            Priority = 2,
                            Title = "Task 1 for Action 2",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 5,
                            ActionId = 2,
                            CreatedOn = new DateTime(2026, 3, 9, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6780),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6781),
                            IsCompleted = true,
                            Priority = 3,
                            Title = "Task 2 for Action 2",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 6,
                            ActionId = 2,
                            CreatedOn = new DateTime(2026, 3, 9, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6783),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6784),
                            IsCompleted = false,
                            Priority = 4,
                            Title = "Task 3 for Action 2",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 7,
                            ActionId = 3,
                            CreatedOn = new DateTime(2026, 3, 9, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6786),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6787),
                            IsCompleted = true,
                            Priority = 1,
                            Title = "Task 1 for Action 3",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 8,
                            ActionId = 3,
                            CreatedOn = new DateTime(2026, 3, 9, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6789),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6789),
                            IsCompleted = false,
                            Priority = 2,
                            Title = "Task 2 for Action 3",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 9,
                            ActionId = 3,
                            CreatedOn = new DateTime(2026, 3, 9, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6791),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6792),
                            IsCompleted = true,
                            Priority = 3,
                            Title = "Task 3 for Action 3",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 10,
                            ActionId = 4,
                            CreatedOn = new DateTime(2026, 3, 9, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6795),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6796),
                            IsCompleted = false,
                            Priority = 4,
                            Title = "Task 1 for Action 4",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 11,
                            ActionId = 4,
                            CreatedOn = new DateTime(2026, 3, 9, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6797),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6798),
                            IsCompleted = true,
                            Priority = 1,
                            Title = "Task 2 for Action 4",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 12,
                            ActionId = 4,
                            CreatedOn = new DateTime(2026, 3, 9, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6799),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6800),
                            IsCompleted = false,
                            Priority = 2,
                            Title = "Task 3 for Action 4",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 13,
                            ActionId = 5,
                            CreatedOn = new DateTime(2026, 3, 9, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6802),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6803),
                            IsCompleted = true,
                            Priority = 3,
                            Title = "Task 1 for Action 5",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 14,
                            ActionId = 5,
                            CreatedOn = new DateTime(2026, 3, 9, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6804),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6805),
                            IsCompleted = false,
                            Priority = 4,
                            Title = "Task 2 for Action 5",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 15,
                            ActionId = 5,
                            CreatedOn = new DateTime(2026, 3, 9, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6807),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6807),
                            IsCompleted = true,
                            Priority = 1,
                            Title = "Task 3 for Action 5",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 16,
                            ActionId = 6,
                            CreatedOn = new DateTime(2026, 3, 9, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6809),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6810),
                            IsCompleted = false,
                            Priority = 2,
                            Title = "Task 1 for Action 6",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 17,
                            ActionId = 6,
                            CreatedOn = new DateTime(2026, 3, 9, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6811),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6812),
                            IsCompleted = true,
                            Priority = 3,
                            Title = "Task 2 for Action 6",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 18,
                            ActionId = 6,
                            CreatedOn = new DateTime(2026, 3, 9, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6814),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6815),
                            IsCompleted = false,
                            Priority = 4,
                            Title = "Task 3 for Action 6",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 19,
                            ActionId = 7,
                            CreatedOn = new DateTime(2026, 3, 9, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6817),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6818),
                            IsCompleted = true,
                            Priority = 1,
                            Title = "Task 1 for Action 7",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 20,
                            ActionId = 7,
                            CreatedOn = new DateTime(2026, 3, 9, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6819),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6820),
                            IsCompleted = false,
                            Priority = 2,
                            Title = "Task 2 for Action 7",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 21,
                            ActionId = 7,
                            CreatedOn = new DateTime(2026, 3, 9, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6822),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6822),
                            IsCompleted = true,
                            Priority = 3,
                            Title = "Task 3 for Action 7",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 22,
                            ActionId = 8,
                            CreatedOn = new DateTime(2026, 3, 9, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6824),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6825),
                            IsCompleted = false,
                            Priority = 4,
                            Title = "Task 1 for Action 8",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 23,
                            ActionId = 8,
                            CreatedOn = new DateTime(2026, 3, 9, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6826),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6827),
                            IsCompleted = true,
                            Priority = 1,
                            Title = "Task 2 for Action 8",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 24,
                            ActionId = 8,
                            CreatedOn = new DateTime(2026, 3, 9, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6828),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6829),
                            IsCompleted = false,
                            Priority = 2,
                            Title = "Task 3 for Action 8",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 25,
                            ActionId = 9,
                            CreatedOn = new DateTime(2026, 3, 9, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6831),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6832),
                            IsCompleted = true,
                            Priority = 3,
                            Title = "Task 1 for Action 9",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 26,
                            ActionId = 9,
                            CreatedOn = new DateTime(2026, 3, 9, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6833),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6834),
                            IsCompleted = false,
                            Priority = 4,
                            Title = "Task 2 for Action 9",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 27,
                            ActionId = 9,
                            CreatedOn = new DateTime(2026, 3, 9, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6835),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6836),
                            IsCompleted = true,
                            Priority = 1,
                            Title = "Task 3 for Action 9",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 28,
                            CreatedOn = new DateTime(2026, 3, 19, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6839),
                            Description = "Unlinked task description",
                            IsCompleted = false,
                            Priority = 2,
                            Title = "General Task 1",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 29,
                            CreatedOn = new DateTime(2026, 3, 19, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6841),
                            Description = "Unlinked task description",
                            IsCompleted = false,
                            Priority = 2,
                            Title = "General Task 2",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 30,
                            CreatedOn = new DateTime(2026, 3, 19, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6842),
                            Description = "Unlinked task description",
                            IsCompleted = false,
                            Priority = 2,
                            Title = "General Task 3",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 31,
                            CreatedOn = new DateTime(2026, 3, 19, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6844),
                            Description = "Unlinked task description",
                            IsCompleted = false,
                            Priority = 2,
                            Title = "General Task 4",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 32,
                            CreatedOn = new DateTime(2026, 3, 19, 17, 42, 21, 229, DateTimeKind.Local).AddTicks(6868),
                            Description = "Unlinked task description",
                            IsCompleted = false,
                            Priority = 2,
                            Title = "General Task 5",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        });
                });

            modelBuilder.Entity("Pathly.DataModels.TaskTag", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("TaskId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TaskTags");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            TagId = 1
                        },
                        new
                        {
                            TaskId = 1,
                            TagId = 10
                        },
                        new
                        {
                            TaskId = 2,
                            TagId = 3
                        },
                        new
                        {
                            TaskId = 4,
                            TagId = 7
                        },
                        new
                        {
                            TaskId = 10,
                            TagId = 5
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Pathly.DataModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Pathly.DataModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pathly.DataModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Pathly.DataModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pathly.DataModels.ActionItem", b =>
                {
                    b.HasOne("Pathly.DataModels.Roadmap", "Roadmap")
                        .WithMany("Actions")
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pathly.DataModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Roadmap");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pathly.DataModels.Goal", b =>
                {
                    b.HasOne("Pathly.DataModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pathly.DataModels.Roadmap", b =>
                {
                    b.HasOne("Pathly.DataModels.Goal", "Goal")
                        .WithOne()
                        .HasForeignKey("Pathly.DataModels.Roadmap", "GoalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pathly.DataModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Goal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pathly.DataModels.Tag", b =>
                {
                    b.HasOne("Pathly.DataModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pathly.DataModels.TaskItem", b =>
                {
                    b.HasOne("Pathly.DataModels.ActionItem", "Action")
                        .WithMany("Tasks")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pathly.DataModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pathly.DataModels.TaskTag", b =>
                {
                    b.HasOne("Pathly.DataModels.Tag", "Tag")
                        .WithMany("TaskTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pathly.DataModels.TaskItem", "Task")
                        .WithMany("TaskTags")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Pathly.DataModels.ActionItem", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Pathly.DataModels.Roadmap", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("Pathly.DataModels.Tag", b =>
                {
                    b.Navigation("TaskTags");
                });

            modelBuilder.Entity("Pathly.DataModels.TaskItem", b =>
                {
                    b.Navigation("TaskTags");
                });
#pragma warning restore 612, 618
        }
    }
}
