// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pathly.Data;

#nullable disable

namespace Pathly.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260404001901_SeedEvents")]
    partial class SeedEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "7f3c9b5e-6c12-4d8a-a6f2-3e9b1c4d8f71",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7210"
                        },
                        new
                        {
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301",
                            RoleId = "7f3c9b5e-6c12-4d8a-a6f2-3e9b1c4d8f71"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Pathly.DataModels.ActionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Resources")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RoadmapId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapId");

                    b.HasIndex("UserId");

                    b.ToTable("Actions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCompleted = true,
                            Resources = "MS Docs, Pluralsight",
                            RoadmapId = 1,
                            Title = "Master EF Core",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 2,
                            IsCompleted = false,
                            Resources = "Docker, RabbitMQ basics",
                            RoadmapId = 1,
                            Title = "Learn Microservices",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 3,
                            IsCompleted = false,
                            Resources = "GoF Book",
                            RoadmapId = 1,
                            Title = "System Design Design Patterns",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 4,
                            IsCompleted = true,
                            Resources = "AutoMapper Guide",
                            RoadmapId = 2,
                            Title = "Implement AutoMapper",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 5,
                            IsCompleted = false,
                            Resources = "xUnit, Moq",
                            RoadmapId = 2,
                            Title = "Setup Unit Tests",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 6,
                            IsCompleted = false,
                            Resources = "Bootstrap, CSS",
                            RoadmapId = 2,
                            Title = "Finalize UI",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 7,
                            IsCompleted = true,
                            RoadmapId = 3,
                            Title = "Basic Syntax",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 8,
                            IsCompleted = true,
                            RoadmapId = 3,
                            Title = "Loops and Arrays",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 9,
                            IsCompleted = true,
                            RoadmapId = 3,
                            Title = "Classes and Objects",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        });
                });

            modelBuilder.Entity("Pathly.DataModels.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3f2504e0-4f89-11d3-9a0c-0305e82c3301",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b2eb3044-b407-4fe7-a4da-8892d64419b8",
                            Email = "test@pathly.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TEST@PATHLY.COM",
                            NormalizedUserName = "TEST@PATHLY.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELRWjfLI2gE/0g6NsVobuFNlWqdqvrlUqLkJHbWzoxUu0wGn4u7Vr9PVuIwgpRfvhQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b89737f1-5589-432c-aeec-9c05c4d83016",
                            TwoFactorEnabled = false,
                            UserName = "test@pathly.com"
                        },
                        new
                        {
                            Id = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e9267e94-405e-4781-a3da-e4f1a4116b20",
                            Email = "admin@pathly.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@PATHLY.COM",
                            NormalizedUserName = "ADMIN@PATHLY.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEINJJfWu7MuHRXuAus7Sh9z2xHIYQT+U7Srhj3kGGzdEP8CyO91AhrVwLPAutJKqSQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b95646c0-2b7c-4f92-9ae3-687779b383f0",
                            TwoFactorEnabled = false,
                            UserName = "admin@pathly.com"
                        });
                });

            modelBuilder.Entity("Pathly.DataModels.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GoalId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorHex = "#4e73df",
                            CreatedOn = new DateTime(2026, 4, 4, 0, 18, 59, 867, DateTimeKind.Utc).AddTicks(1939),
                            Description = "Planning for the new quarter",
                            End = new DateTime(2026, 4, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            GoalId = 1,
                            IsAllDay = false,
                            Start = new DateTime(2026, 4, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Q2 Kickoff",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 2,
                            ColorHex = "#1cc88a",
                            CreatedOn = new DateTime(2026, 4, 4, 0, 18, 59, 867, DateTimeKind.Utc).AddTicks(1946),
                            Description = "No interruptions allowed",
                            End = new DateTime(2026, 4, 3, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAllDay = false,
                            Start = new DateTime(2026, 4, 3, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Deep Work: Coding",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 3,
                            ColorHex = "#f6c23e",
                            CreatedOn = new DateTime(2026, 4, 4, 0, 18, 59, 867, DateTimeKind.Utc).AddTicks(1948),
                            End = new DateTime(2026, 4, 12, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAllDay = false,
                            Start = new DateTime(2026, 4, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Productivity Seminar",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 4,
                            ColorHex = "#36b9cc",
                            CreatedOn = new DateTime(2026, 4, 4, 0, 18, 59, 867, DateTimeKind.Utc).AddTicks(1951),
                            Description = "Sync with the roadmap",
                            End = new DateTime(2026, 4, 15, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAllDay = false,
                            Start = new DateTime(2026, 4, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mid-April Check-in",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 5,
                            ColorHex = "#e74a3b",
                            CreatedOn = new DateTime(2026, 4, 4, 0, 18, 59, 867, DateTimeKind.Utc).AddTicks(1952),
                            End = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAllDay = true,
                            Start = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Easter Sunday",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 6,
                            ColorHex = "#5a5c69",
                            CreatedOn = new DateTime(2026, 4, 4, 0, 18, 59, 867, DateTimeKind.Utc).AddTicks(1959),
                            Description = "Team updates",
                            End = new DateTime(2026, 4, 21, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAllDay = false,
                            Start = new DateTime(2026, 4, 21, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Morning Sync",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 7,
                            ColorHex = "#6610f2",
                            CreatedOn = new DateTime(2026, 4, 4, 0, 18, 59, 867, DateTimeKind.Utc).AddTicks(1960),
                            Description = "New tech stack",
                            End = new DateTime(2026, 4, 21, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAllDay = false,
                            Start = new DateTime(2026, 4, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Lunch & Learn",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 8,
                            ColorHex = "#4e73df",
                            CreatedOn = new DateTime(2026, 4, 4, 0, 18, 59, 867, DateTimeKind.Utc).AddTicks(1962),
                            Description = "Project Alpha",
                            End = new DateTime(2026, 4, 21, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAllDay = false,
                            Start = new DateTime(2026, 4, 21, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Client Call",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 9,
                            ColorHex = "#858796",
                            CreatedOn = new DateTime(2026, 4, 4, 0, 18, 59, 867, DateTimeKind.Utc).AddTicks(1963),
                            Description = "Updating schema",
                            End = new DateTime(2026, 4, 29, 1, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAllDay = false,
                            Start = new DateTime(2026, 4, 28, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "DB Migration",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 10,
                            ColorHex = "#1cc88a",
                            CreatedOn = new DateTime(2026, 4, 4, 0, 18, 59, 867, DateTimeKind.Utc).AddTicks(1966),
                            Description = "Clearing the backlog",
                            End = new DateTime(2026, 4, 30, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAllDay = false,
                            Start = new DateTime(2026, 4, 30, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskId = 10,
                            Title = "April Task Sweep",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 11,
                            ColorHex = "#e74a3b",
                            CreatedOn = new DateTime(2026, 4, 4, 0, 18, 59, 867, DateTimeKind.Utc).AddTicks(1967),
                            End = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAllDay = true,
                            Start = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Labour Day Holiday",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 12,
                            ColorHex = "#36b9cc",
                            CreatedOn = new DateTime(2026, 4, 4, 0, 18, 59, 867, DateTimeKind.Utc).AddTicks(1969),
                            Description = "Design work",
                            End = new DateTime(2026, 5, 4, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAllDay = false,
                            Start = new DateTime(2026, 5, 4, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Focus Block A",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 13,
                            ColorHex = "#e74a3b",
                            CreatedOn = new DateTime(2026, 4, 4, 0, 18, 59, 867, DateTimeKind.Utc).AddTicks(1970),
                            Description = "Bug fix",
                            End = new DateTime(2026, 5, 4, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAllDay = false,
                            Start = new DateTime(2026, 5, 4, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Emergency Meeting",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 14,
                            ColorHex = "#5a5c69",
                            CreatedOn = new DateTime(2026, 4, 4, 0, 18, 59, 867, DateTimeKind.Utc).AddTicks(1971),
                            Description = "Daily standup",
                            End = new DateTime(2026, 5, 4, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAllDay = false,
                            Start = new DateTime(2026, 5, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Quick Sync",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 15,
                            ColorHex = "#6610f2",
                            CreatedOn = new DateTime(2026, 4, 4, 0, 18, 59, 867, DateTimeKind.Utc).AddTicks(1973),
                            Description = "Celebrating achievement",
                            End = new DateTime(2026, 5, 12, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            GoalId = 2,
                            IsAllDay = false,
                            Start = new DateTime(2026, 5, 12, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Goal #2 Milestone",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 16,
                            ColorHex = "#1cc88a",
                            CreatedOn = new DateTime(2026, 4, 4, 0, 18, 59, 867, DateTimeKind.Utc).AddTicks(1974),
                            Description = "Upskilling in .NET Testing",
                            End = new DateTime(2026, 5, 22, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAllDay = true,
                            Start = new DateTime(2026, 5, 18, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Learning Week",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 17,
                            ColorHex = "#f6c23e",
                            CreatedOn = new DateTime(2026, 4, 4, 0, 18, 59, 867, DateTimeKind.Utc).AddTicks(1976),
                            Description = "Wireframing session",
                            End = new DateTime(2026, 5, 25, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAllDay = false,
                            Start = new DateTime(2026, 5, 25, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "UX Workshop",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 18,
                            ColorHex = "#858796",
                            CreatedOn = new DateTime(2026, 4, 4, 0, 18, 59, 867, DateTimeKind.Utc).AddTicks(1978),
                            Description = "Friday Wrap-up",
                            End = new DateTime(2026, 5, 29, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAllDay = false,
                            Start = new DateTime(2026, 5, 29, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskId = 5,
                            Title = "Weekly Report",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 19,
                            ColorHex = "#4e73df",
                            CreatedOn = new DateTime(2026, 4, 4, 0, 18, 59, 867, DateTimeKind.Utc).AddTicks(1979),
                            Description = "Reviewing May performance",
                            End = new DateTime(2026, 5, 31, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAllDay = false,
                            Start = new DateTime(2026, 5, 31, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "May Summary",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 20,
                            ColorHex = "#36b9cc",
                            CreatedOn = new DateTime(2026, 4, 4, 0, 18, 59, 867, DateTimeKind.Utc).AddTicks(1980),
                            Description = "Late night productivity",
                            End = new DateTime(2026, 6, 1, 1, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAllDay = false,
                            Start = new DateTime(2026, 5, 31, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Side Project Push",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        });
                });

            modelBuilder.Entity("Pathly.DataModels.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Goals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            ShortDescription = "Mastering advanced architecture and cloud services in the .NET ecosystem.",
                            TargetDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Become a Senior .NET Developer",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            ShortDescription = "Complete the implementation of AutoMapper and Seeding in the current project.",
                            TargetDate = new DateTime(2026, 5, 4, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(979),
                            Title = "Master Pathly Architecture",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = false,
                            ShortDescription = "Successfully finished the basics of C# programming.",
                            TargetDate = new DateTime(2025, 11, 4, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1040),
                            Title = "SoftUni Fundamentals Module",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        });
                });

            modelBuilder.Entity("Pathly.DataModels.Roadmap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GoalId")
                        .HasColumnType("int");

                    b.Property<string>("IdealOutcome")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Why")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("GoalId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Roadmaps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GoalId = 1,
                            IdealOutcome = "Senior Dev Role",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301",
                            Why = "To achieve financial independence"
                        },
                        new
                        {
                            Id = 2,
                            GoalId = 2,
                            IdealOutcome = "Perfectly coded app",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301",
                            Why = "To build professional habits"
                        },
                        new
                        {
                            Id = 3,
                            GoalId = 3,
                            IdealOutcome = "Solid programming basics",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301",
                            Why = "Foundation is key"
                        });
                });

            modelBuilder.Entity("Pathly.DataModels.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Work",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Personal",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 3,
                            Name = "C#",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gym",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Frontend",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Testing",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Learning",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Soft Skill",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 9,
                            Name = "School",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Urgent",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        });
                });

            modelBuilder.Entity("Pathly.DataModels.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionId = 1,
                            CreatedOn = new DateTime(2026, 3, 25, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1389),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 4, 9, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1394),
                            IsCompleted = true,
                            Position = 0,
                            Priority = 3,
                            Status = 0,
                            Title = "Task 1 for Action 1",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 2,
                            ActionId = 1,
                            CreatedOn = new DateTime(2026, 3, 25, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1402),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 4, 9, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1406),
                            IsCompleted = false,
                            Position = 0,
                            Priority = 4,
                            Status = 0,
                            Title = "Task 2 for Action 1",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 3,
                            ActionId = 1,
                            CreatedOn = new DateTime(2026, 3, 25, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1415),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 4, 9, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1416),
                            IsCompleted = true,
                            Position = 0,
                            Priority = 1,
                            Status = 0,
                            Title = "Task 3 for Action 1",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 4,
                            ActionId = 2,
                            CreatedOn = new DateTime(2026, 3, 25, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1418),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 4, 9, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1420),
                            IsCompleted = false,
                            Position = 0,
                            Priority = 2,
                            Status = 0,
                            Title = "Task 1 for Action 2",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 5,
                            ActionId = 2,
                            CreatedOn = new DateTime(2026, 3, 25, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1424),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 4, 9, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1428),
                            IsCompleted = true,
                            Position = 0,
                            Priority = 3,
                            Status = 0,
                            Title = "Task 2 for Action 2",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 6,
                            ActionId = 2,
                            CreatedOn = new DateTime(2026, 3, 25, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1432),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 4, 9, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1433),
                            IsCompleted = false,
                            Position = 0,
                            Priority = 4,
                            Status = 0,
                            Title = "Task 3 for Action 2",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 7,
                            ActionId = 3,
                            CreatedOn = new DateTime(2026, 3, 25, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1435),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 4, 9, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1456),
                            IsCompleted = true,
                            Position = 0,
                            Priority = 1,
                            Status = 0,
                            Title = "Task 1 for Action 3",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 8,
                            ActionId = 3,
                            CreatedOn = new DateTime(2026, 3, 25, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1458),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 4, 9, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1460),
                            IsCompleted = false,
                            Position = 0,
                            Priority = 2,
                            Status = 0,
                            Title = "Task 2 for Action 3",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 9,
                            ActionId = 3,
                            CreatedOn = new DateTime(2026, 3, 25, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1462),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 4, 9, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1463),
                            IsCompleted = true,
                            Position = 0,
                            Priority = 3,
                            Status = 0,
                            Title = "Task 3 for Action 3",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 10,
                            ActionId = 4,
                            CreatedOn = new DateTime(2026, 3, 25, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1470),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 4, 9, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1471),
                            IsCompleted = false,
                            Position = 0,
                            Priority = 4,
                            Status = 0,
                            Title = "Task 1 for Action 4",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 11,
                            ActionId = 4,
                            CreatedOn = new DateTime(2026, 3, 25, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1474),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 4, 9, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1475),
                            IsCompleted = true,
                            Position = 0,
                            Priority = 1,
                            Status = 0,
                            Title = "Task 2 for Action 4",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 12,
                            ActionId = 4,
                            CreatedOn = new DateTime(2026, 3, 25, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1477),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 4, 9, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1478),
                            IsCompleted = false,
                            Position = 0,
                            Priority = 2,
                            Status = 0,
                            Title = "Task 3 for Action 4",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 13,
                            ActionId = 5,
                            CreatedOn = new DateTime(2026, 3, 25, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1480),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 4, 9, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1481),
                            IsCompleted = true,
                            Position = 0,
                            Priority = 3,
                            Status = 0,
                            Title = "Task 1 for Action 5",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 14,
                            ActionId = 5,
                            CreatedOn = new DateTime(2026, 3, 25, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1483),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 4, 9, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1487),
                            IsCompleted = false,
                            Position = 0,
                            Priority = 4,
                            Status = 0,
                            Title = "Task 2 for Action 5",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 15,
                            ActionId = 5,
                            CreatedOn = new DateTime(2026, 3, 25, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1531),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 4, 9, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1533),
                            IsCompleted = true,
                            Position = 0,
                            Priority = 1,
                            Status = 0,
                            Title = "Task 3 for Action 5",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 16,
                            ActionId = 6,
                            CreatedOn = new DateTime(2026, 3, 25, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1538),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 4, 9, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1539),
                            IsCompleted = false,
                            Position = 0,
                            Priority = 2,
                            Status = 0,
                            Title = "Task 1 for Action 6",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 17,
                            ActionId = 6,
                            CreatedOn = new DateTime(2026, 3, 25, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1541),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 4, 9, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1542),
                            IsCompleted = true,
                            Position = 0,
                            Priority = 3,
                            Status = 0,
                            Title = "Task 2 for Action 6",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 18,
                            ActionId = 6,
                            CreatedOn = new DateTime(2026, 3, 25, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1545),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 4, 9, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1546),
                            IsCompleted = false,
                            Position = 0,
                            Priority = 4,
                            Status = 0,
                            Title = "Task 3 for Action 6",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 19,
                            ActionId = 7,
                            CreatedOn = new DateTime(2026, 3, 25, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1552),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 4, 9, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1553),
                            IsCompleted = true,
                            Position = 0,
                            Priority = 1,
                            Status = 0,
                            Title = "Task 1 for Action 7",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 20,
                            ActionId = 7,
                            CreatedOn = new DateTime(2026, 3, 25, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1555),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 4, 9, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1556),
                            IsCompleted = false,
                            Position = 0,
                            Priority = 2,
                            Status = 0,
                            Title = "Task 2 for Action 7",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 21,
                            ActionId = 7,
                            CreatedOn = new DateTime(2026, 3, 25, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1558),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 4, 9, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1560),
                            IsCompleted = true,
                            Position = 0,
                            Priority = 3,
                            Status = 0,
                            Title = "Task 3 for Action 7",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 22,
                            ActionId = 8,
                            CreatedOn = new DateTime(2026, 3, 25, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1595),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 4, 9, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1597),
                            IsCompleted = false,
                            Position = 0,
                            Priority = 4,
                            Status = 0,
                            Title = "Task 1 for Action 8",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 23,
                            ActionId = 8,
                            CreatedOn = new DateTime(2026, 3, 25, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1601),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 4, 9, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1603),
                            IsCompleted = true,
                            Position = 0,
                            Priority = 1,
                            Status = 0,
                            Title = "Task 2 for Action 8",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 24,
                            ActionId = 8,
                            CreatedOn = new DateTime(2026, 3, 25, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1606),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 4, 9, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1608),
                            IsCompleted = false,
                            Position = 0,
                            Priority = 2,
                            Status = 0,
                            Title = "Task 3 for Action 8",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 25,
                            ActionId = 9,
                            CreatedOn = new DateTime(2026, 3, 25, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1611),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 4, 9, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1612),
                            IsCompleted = true,
                            Position = 0,
                            Priority = 3,
                            Status = 0,
                            Title = "Task 1 for Action 9",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 26,
                            ActionId = 9,
                            CreatedOn = new DateTime(2026, 3, 25, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1615),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 4, 9, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1617),
                            IsCompleted = false,
                            Position = 0,
                            Priority = 4,
                            Status = 0,
                            Title = "Task 2 for Action 9",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 27,
                            ActionId = 9,
                            CreatedOn = new DateTime(2026, 3, 25, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1621),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 4, 9, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1623),
                            IsCompleted = true,
                            Position = 0,
                            Priority = 1,
                            Status = 0,
                            Title = "Task 3 for Action 9",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 28,
                            CreatedOn = new DateTime(2026, 4, 4, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1633),
                            Description = "Unlinked task description",
                            IsCompleted = false,
                            Position = 0,
                            Priority = 2,
                            Status = 0,
                            Title = "General Task 1",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 29,
                            CreatedOn = new DateTime(2026, 4, 4, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1637),
                            Description = "Unlinked task description",
                            IsCompleted = false,
                            Position = 0,
                            Priority = 2,
                            Status = 0,
                            Title = "General Task 2",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 30,
                            CreatedOn = new DateTime(2026, 4, 4, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1665),
                            Description = "Unlinked task description",
                            IsCompleted = false,
                            Position = 0,
                            Priority = 2,
                            Status = 0,
                            Title = "General Task 3",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 31,
                            CreatedOn = new DateTime(2026, 4, 4, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1668),
                            Description = "Unlinked task description",
                            IsCompleted = false,
                            Position = 0,
                            Priority = 2,
                            Status = 0,
                            Title = "General Task 4",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 32,
                            CreatedOn = new DateTime(2026, 4, 4, 3, 18, 59, 867, DateTimeKind.Local).AddTicks(1671),
                            Description = "Unlinked task description",
                            IsCompleted = false,
                            Position = 0,
                            Priority = 2,
                            Status = 0,
                            Title = "General Task 5",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        });
                });

            modelBuilder.Entity("Pathly.DataModels.TaskTag", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("TaskId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TaskTags");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            TagId = 1
                        },
                        new
                        {
                            TaskId = 1,
                            TagId = 10
                        },
                        new
                        {
                            TaskId = 2,
                            TagId = 3
                        },
                        new
                        {
                            TaskId = 4,
                            TagId = 7
                        },
                        new
                        {
                            TaskId = 10,
                            TagId = 5
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Pathly.DataModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Pathly.DataModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pathly.DataModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Pathly.DataModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pathly.DataModels.ActionItem", b =>
                {
                    b.HasOne("Pathly.DataModels.Roadmap", "Roadmap")
                        .WithMany("Actions")
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pathly.DataModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Roadmap");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pathly.DataModels.Event", b =>
                {
                    b.HasOne("Pathly.DataModels.Goal", "Goal")
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pathly.DataModels.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pathly.DataModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Goal");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pathly.DataModels.Goal", b =>
                {
                    b.HasOne("Pathly.DataModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pathly.DataModels.Roadmap", b =>
                {
                    b.HasOne("Pathly.DataModels.Goal", "Goal")
                        .WithOne("Roadmap")
                        .HasForeignKey("Pathly.DataModels.Roadmap", "GoalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pathly.DataModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Goal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pathly.DataModels.Tag", b =>
                {
                    b.HasOne("Pathly.DataModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pathly.DataModels.TaskItem", b =>
                {
                    b.HasOne("Pathly.DataModels.ActionItem", "Action")
                        .WithMany("Tasks")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pathly.DataModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pathly.DataModels.TaskTag", b =>
                {
                    b.HasOne("Pathly.DataModels.Tag", "Tag")
                        .WithMany("TaskTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pathly.DataModels.TaskItem", "Task")
                        .WithMany("TaskTags")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Pathly.DataModels.ActionItem", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Pathly.DataModels.Goal", b =>
                {
                    b.Navigation("Roadmap");
                });

            modelBuilder.Entity("Pathly.DataModels.Roadmap", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("Pathly.DataModels.Tag", b =>
                {
                    b.Navigation("TaskTags");
                });

            modelBuilder.Entity("Pathly.DataModels.TaskItem", b =>
                {
                    b.Navigation("TaskTags");
                });
#pragma warning restore 612, 618
        }
    }
}
