// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pathly.Data;

#nullable disable

namespace Pathly.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260319202359_FixGoalRoadmapRelationship")]
    partial class FixGoalRoadmapRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Pathly.DataModels.ActionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Resources")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RoadmapId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapId");

                    b.HasIndex("UserId");

                    b.ToTable("Actions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCompleted = true,
                            Resources = "MS Docs, Pluralsight",
                            RoadmapId = 1,
                            Title = "Master EF Core",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 2,
                            IsCompleted = false,
                            Resources = "Docker, RabbitMQ basics",
                            RoadmapId = 1,
                            Title = "Learn Microservices",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 3,
                            IsCompleted = false,
                            Resources = "GoF Book",
                            RoadmapId = 1,
                            Title = "System Design Design Patterns",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 4,
                            IsCompleted = true,
                            Resources = "AutoMapper Guide",
                            RoadmapId = 2,
                            Title = "Implement AutoMapper",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 5,
                            IsCompleted = false,
                            Resources = "xUnit, Moq",
                            RoadmapId = 2,
                            Title = "Setup Unit Tests",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 6,
                            IsCompleted = false,
                            Resources = "Bootstrap, CSS",
                            RoadmapId = 2,
                            Title = "Finalize UI",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 7,
                            IsCompleted = true,
                            RoadmapId = 3,
                            Title = "Basic Syntax",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 8,
                            IsCompleted = true,
                            RoadmapId = 3,
                            Title = "Loops and Arrays",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 9,
                            IsCompleted = true,
                            RoadmapId = 3,
                            Title = "Classes and Objects",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        });
                });

            modelBuilder.Entity("Pathly.DataModels.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3f2504e0-4f89-11d3-9a0c-0305e82c3301",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4d6feb5e-4b0e-4257-8c3c-3b2a60642ea5",
                            Email = "test@pathly.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TEST@PATHLY.COM",
                            NormalizedUserName = "TEST@PATHLY.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEK+1AN+2OYbWgwIX++Y6QbwiDo6L9a5IzNUAXd75xvbGB4FTLXH3QOTw3Dh3YpZwqw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "00644c98-cce0-4d3b-ac0c-5cb3113a4f5a",
                            TwoFactorEnabled = false,
                            UserName = "test@pathly.com"
                        });
                });

            modelBuilder.Entity("Pathly.DataModels.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Goals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            ShortDescription = "Mastering advanced architecture and cloud services in the .NET ecosystem.",
                            TargetDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Become a Senior .NET Developer",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            ShortDescription = "Complete the implementation of AutoMapper and Seeding in the current project.",
                            TargetDate = new DateTime(2026, 4, 19, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(3921),
                            Title = "Master Pathly Architecture",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = false,
                            ShortDescription = "Successfully finished the basics of C# programming.",
                            TargetDate = new DateTime(2025, 10, 19, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(3964),
                            Title = "SoftUni Fundamentals Module",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        });
                });

            modelBuilder.Entity("Pathly.DataModels.Roadmap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GoalId")
                        .HasColumnType("int");

                    b.Property<string>("IdealOutcome")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Why")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("GoalId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Roadmaps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GoalId = 1,
                            IdealOutcome = "Senior Dev Role",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301",
                            Why = "To achieve financial independence"
                        },
                        new
                        {
                            Id = 2,
                            GoalId = 2,
                            IdealOutcome = "Perfectly coded app",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301",
                            Why = "To build professional habits"
                        },
                        new
                        {
                            Id = 3,
                            GoalId = 3,
                            IdealOutcome = "Solid programming basics",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301",
                            Why = "Foundation is key"
                        });
                });

            modelBuilder.Entity("Pathly.DataModels.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Work",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Personal",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 3,
                            Name = "C#",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gym",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Frontend",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Testing",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Learning",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Soft Skill",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 9,
                            Name = "School",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Urgent",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        });
                });

            modelBuilder.Entity("Pathly.DataModels.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionId = 1,
                            CreatedOn = new DateTime(2026, 3, 9, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4313),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4317),
                            IsCompleted = true,
                            Priority = 3,
                            Title = "Task 1 for Action 1",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 2,
                            ActionId = 1,
                            CreatedOn = new DateTime(2026, 3, 9, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4322),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4323),
                            IsCompleted = false,
                            Priority = 4,
                            Title = "Task 2 for Action 1",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 3,
                            ActionId = 1,
                            CreatedOn = new DateTime(2026, 3, 9, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4325),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4326),
                            IsCompleted = true,
                            Priority = 1,
                            Title = "Task 3 for Action 1",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 4,
                            ActionId = 2,
                            CreatedOn = new DateTime(2026, 3, 9, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4328),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4329),
                            IsCompleted = false,
                            Priority = 2,
                            Title = "Task 1 for Action 2",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 5,
                            ActionId = 2,
                            CreatedOn = new DateTime(2026, 3, 9, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4331),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4332),
                            IsCompleted = true,
                            Priority = 3,
                            Title = "Task 2 for Action 2",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 6,
                            ActionId = 2,
                            CreatedOn = new DateTime(2026, 3, 9, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4335),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4336),
                            IsCompleted = false,
                            Priority = 4,
                            Title = "Task 3 for Action 2",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 7,
                            ActionId = 3,
                            CreatedOn = new DateTime(2026, 3, 9, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4338),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4339),
                            IsCompleted = true,
                            Priority = 1,
                            Title = "Task 1 for Action 3",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 8,
                            ActionId = 3,
                            CreatedOn = new DateTime(2026, 3, 9, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4341),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4341),
                            IsCompleted = false,
                            Priority = 2,
                            Title = "Task 2 for Action 3",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 9,
                            ActionId = 3,
                            CreatedOn = new DateTime(2026, 3, 9, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4343),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4344),
                            IsCompleted = true,
                            Priority = 3,
                            Title = "Task 3 for Action 3",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 10,
                            ActionId = 4,
                            CreatedOn = new DateTime(2026, 3, 9, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4347),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4347),
                            IsCompleted = false,
                            Priority = 4,
                            Title = "Task 1 for Action 4",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 11,
                            ActionId = 4,
                            CreatedOn = new DateTime(2026, 3, 9, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4349),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4350),
                            IsCompleted = true,
                            Priority = 1,
                            Title = "Task 2 for Action 4",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 12,
                            ActionId = 4,
                            CreatedOn = new DateTime(2026, 3, 9, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4352),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4352),
                            IsCompleted = false,
                            Priority = 2,
                            Title = "Task 3 for Action 4",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 13,
                            ActionId = 5,
                            CreatedOn = new DateTime(2026, 3, 9, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4354),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4355),
                            IsCompleted = true,
                            Priority = 3,
                            Title = "Task 1 for Action 5",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 14,
                            ActionId = 5,
                            CreatedOn = new DateTime(2026, 3, 9, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4357),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4358),
                            IsCompleted = false,
                            Priority = 4,
                            Title = "Task 2 for Action 5",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 15,
                            ActionId = 5,
                            CreatedOn = new DateTime(2026, 3, 9, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4360),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4360),
                            IsCompleted = true,
                            Priority = 1,
                            Title = "Task 3 for Action 5",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 16,
                            ActionId = 6,
                            CreatedOn = new DateTime(2026, 3, 9, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4362),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4363),
                            IsCompleted = false,
                            Priority = 2,
                            Title = "Task 1 for Action 6",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 17,
                            ActionId = 6,
                            CreatedOn = new DateTime(2026, 3, 9, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4365),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4366),
                            IsCompleted = true,
                            Priority = 3,
                            Title = "Task 2 for Action 6",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 18,
                            ActionId = 6,
                            CreatedOn = new DateTime(2026, 3, 9, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4368),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4369),
                            IsCompleted = false,
                            Priority = 4,
                            Title = "Task 3 for Action 6",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 19,
                            ActionId = 7,
                            CreatedOn = new DateTime(2026, 3, 9, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4371),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4372),
                            IsCompleted = true,
                            Priority = 1,
                            Title = "Task 1 for Action 7",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 20,
                            ActionId = 7,
                            CreatedOn = new DateTime(2026, 3, 9, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4374),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4375),
                            IsCompleted = false,
                            Priority = 2,
                            Title = "Task 2 for Action 7",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 21,
                            ActionId = 7,
                            CreatedOn = new DateTime(2026, 3, 9, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4376),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4377),
                            IsCompleted = true,
                            Priority = 3,
                            Title = "Task 3 for Action 7",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 22,
                            ActionId = 8,
                            CreatedOn = new DateTime(2026, 3, 9, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4379),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4380),
                            IsCompleted = false,
                            Priority = 4,
                            Title = "Task 1 for Action 8",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 23,
                            ActionId = 8,
                            CreatedOn = new DateTime(2026, 3, 9, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4381),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4382),
                            IsCompleted = true,
                            Priority = 1,
                            Title = "Task 2 for Action 8",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 24,
                            ActionId = 8,
                            CreatedOn = new DateTime(2026, 3, 9, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4384),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4385),
                            IsCompleted = false,
                            Priority = 2,
                            Title = "Task 3 for Action 8",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 25,
                            ActionId = 9,
                            CreatedOn = new DateTime(2026, 3, 9, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4387),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4387),
                            IsCompleted = true,
                            Priority = 3,
                            Title = "Task 1 for Action 9",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 26,
                            ActionId = 9,
                            CreatedOn = new DateTime(2026, 3, 9, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4389),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4390),
                            IsCompleted = false,
                            Priority = 4,
                            Title = "Task 2 for Action 9",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 27,
                            ActionId = 9,
                            CreatedOn = new DateTime(2026, 3, 9, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4415),
                            Description = "Seed description",
                            DueDate = new DateTime(2026, 3, 24, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4416),
                            IsCompleted = true,
                            Priority = 1,
                            Title = "Task 3 for Action 9",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 28,
                            CreatedOn = new DateTime(2026, 3, 19, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4420),
                            Description = "Unlinked task description",
                            IsCompleted = false,
                            Priority = 2,
                            Title = "General Task 1",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 29,
                            CreatedOn = new DateTime(2026, 3, 19, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4423),
                            Description = "Unlinked task description",
                            IsCompleted = false,
                            Priority = 2,
                            Title = "General Task 2",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 30,
                            CreatedOn = new DateTime(2026, 3, 19, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4424),
                            Description = "Unlinked task description",
                            IsCompleted = false,
                            Priority = 2,
                            Title = "General Task 3",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 31,
                            CreatedOn = new DateTime(2026, 3, 19, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4426),
                            Description = "Unlinked task description",
                            IsCompleted = false,
                            Priority = 2,
                            Title = "General Task 4",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        },
                        new
                        {
                            Id = 32,
                            CreatedOn = new DateTime(2026, 3, 19, 22, 23, 58, 841, DateTimeKind.Local).AddTicks(4427),
                            Description = "Unlinked task description",
                            IsCompleted = false,
                            Priority = 2,
                            Title = "General Task 5",
                            UserId = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                        });
                });

            modelBuilder.Entity("Pathly.DataModels.TaskTag", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("TaskId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TaskTags");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            TagId = 1
                        },
                        new
                        {
                            TaskId = 1,
                            TagId = 10
                        },
                        new
                        {
                            TaskId = 2,
                            TagId = 3
                        },
                        new
                        {
                            TaskId = 4,
                            TagId = 7
                        },
                        new
                        {
                            TaskId = 10,
                            TagId = 5
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Pathly.DataModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Pathly.DataModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pathly.DataModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Pathly.DataModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pathly.DataModels.ActionItem", b =>
                {
                    b.HasOne("Pathly.DataModels.Roadmap", "Roadmap")
                        .WithMany("Actions")
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pathly.DataModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Roadmap");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pathly.DataModels.Goal", b =>
                {
                    b.HasOne("Pathly.DataModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pathly.DataModels.Roadmap", b =>
                {
                    b.HasOne("Pathly.DataModels.Goal", "Goal")
                        .WithOne("Roadmap")
                        .HasForeignKey("Pathly.DataModels.Roadmap", "GoalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pathly.DataModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Goal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pathly.DataModels.Tag", b =>
                {
                    b.HasOne("Pathly.DataModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pathly.DataModels.TaskItem", b =>
                {
                    b.HasOne("Pathly.DataModels.ActionItem", "Action")
                        .WithMany("Tasks")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pathly.DataModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pathly.DataModels.TaskTag", b =>
                {
                    b.HasOne("Pathly.DataModels.Tag", "Tag")
                        .WithMany("TaskTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pathly.DataModels.TaskItem", "Task")
                        .WithMany("TaskTags")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Pathly.DataModels.ActionItem", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Pathly.DataModels.Goal", b =>
                {
                    b.Navigation("Roadmap");
                });

            modelBuilder.Entity("Pathly.DataModels.Roadmap", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("Pathly.DataModels.Tag", b =>
                {
                    b.Navigation("TaskTags");
                });

            modelBuilder.Entity("Pathly.DataModels.TaskItem", b =>
                {
                    b.Navigation("TaskTags");
                });
#pragma warning restore 612, 618
        }
    }
}
